version: "3.8"

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_HOST=trimorphous-nonacoustically-halley.ngrok-free.dev
      - WEBHOOK_URL=https://trimorphous-nonacoustically-halley.ngrok-free.dev
      - NODE_ENV=production
    depends_on:
      - ngrok

  ngrok:
    image: ngrok/ngrok
    container_name: ngrok
    restart: unless-stopped
    command: http n8n:5678
    environment:
      - NGROK_AUTHTOKEN="37LD184jLtVv45BT3m9iZtHzplZ_4krjVWFBDxHg8cBVRMD1r"